from openai import OpenAI


def get_response_from_openAi(open_ai_key, prompt):
    """
    Get a response from OpenAI using the provided client and prompt.

    Parameters:
    open_ai_client (object): The OpenAI client object with chat completion capabilities.
    prompt (dict): A dictionary containing the prompt messages.

    Returns:
    str: The response generated by the OpenAI model.
    """
    try:
        # Initialize the OpenAI client
        client = OpenAI(api_key=open_ai_key)

        # Extract the 'messages' list from the prompt dictionary
        messages = prompt['messages']

        # Create a chat completion request using the OpenAI client
        stream = client.chat.completions.create(
            model="gpt-4-turbo",
            messages=messages,
            stream=True,
        )

        # Initialize an empty string to store the accumulated response data
        response_data = ""

        # Iterate over the streamed response chunks
        for chunk in stream:
            # Check if the chunk contains a non-None content delta
            if chunk.choices[0].delta.content is not None:
                # Append the content of the chunk to the response data string
                response_data += chunk.choices[0].delta.content

        # Return the complete response data
        return response_data
    except ImportError as e:
        print(f"ImportError: {e}")
        return None
    except Exception as e:
        print(f"An error occurred: {e}")
        return None
    


    
